# CodeRabbit configuration
language: "ja-JP"

reviews:
  auto_review: true
  draft_pr: false
  high_level_summary: true
  poem: false
  review_status: true
  collapse_empty_sections: false
  request_changes_workflow: true
  enable_free_tier: true

# Language and output settings
output:
  language: "ja-JP"
  locale: "ja-JP"

# VSCode extension specific settings
vscode:
  language: "ja-JP"
  comments_language: "ja-JP"

chat:
  auto_reply: true

rules:
  - path: "**/*.ts"
    reviewers: auto
  - path: "**/*.tsx" 
    reviewers: auto
  - path: "**/*.js"
    reviewers: auto
  - path: "**/*.jsx"
    reviewers: auto

ignore:
  - "node_modules/**"
  - ".next/**"
  - "dist/**" 
  - "build/**"
  - "coverage/**"
  - "*.lock"
  - "package-lock.json"

base_branches:
  - main
  - master