name = "tournament-system"
compatibility_date = "2024-07-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run pages:build"
cwd = "."

[build.environment_variables]
NODE_VERSION = "18"