name = "tournament-system"
compatibility_date = "2024-07-01"
compatibility_flags = ["nodejs_compat"]

# Build configuration is handled by Cloudflare Pages dashboard
# No pages_build_output_dir needed when using Git integration